# This is a basic workflow to help you get started with Actions

name: Araba Build and Test 

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          touch araba.txt
          echo "kaporta" >> araba.txt
          echo "motor" >> araba.txt
          echo "tekerlekler" >> araba.txt

      - name: araba.txt -> artifacts lere koy
        uses: actions/upload-artifact@v2
        with:
          name: araba build sonucu ortaya cikan araba.txt
          path: araba.txt 

  test:
    needs: build 
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: araba.txt ini artifacts lerden al
        uses: actions/download-artifact@v2
        with:
          name: araba build sonucu ortaya cikan araba.txt
          

      # Runs a single command using the runners shell
      - name: Run multiple-lines script
        run: | 
          grep "kaporta" araba.txt
          grep "motor" araba.txt
          grep "tekerlekler" araba.txt



